CREATE SCHEMA flashcard_webapp CHAR SET utf8mb4;
USE flashcard_webapp;

DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER`
(
  ID 			BIGINT 			AUTO_INCREMENT 		PRIMARY KEY,
  `NAME` 		VARCHAR(255)	NOT NULL,
  EMAIL 		VARCHAR(255) 	NOT NULL,
  `PASSWORD` 	VARCHAR(255) 	NOT NULL,
  `ROLE` 		VARCHAR(50) 	NOT NULL
);

DROP TABLE IF EXISTS `FLASHCARD`;
CREATE TABLE `FLASHCARD`
(
  ID 				BIGINT 			AUTO_INCREMENT 		PRIMARY KEY,
  `NAME` 			VARCHAR(255) 	NOT NULL,
  `DESCRIPTION` 	TEXT,
  USER_ID 			BIGINT
);
ALTER TABLE `FLASHCARD`
ADD CONSTRAINT FK_FLASHCARD_USER 	FOREIGN KEY (USER_ID) 	REFERENCES `USER`(ID);

DROP TABLE IF EXISTS `CARD`;
CREATE TABLE `CARD`
(
  ID 			BIGINT 			AUTO_INCREMENT PRIMARY KEY,
  `NAME` 		VARCHAR(255) 	NOT NULL,
  `DEFINATION` 	TEXT,
  FLASHCARD_ID	BIGINT
);
ALTER TABLE `CARD`
ADD CONSTRAINT FK_CARD_LASHCARD	FOREIGN KEY (FLASHCARD_ID) 	REFERENCES `FLASHCARD`(ID);
